import SonyWalkmanImg from "../assets/f56678e9-22c5-4b57-9c19-8114f6060e5d.png";
import SennheiserHD414Img from "../assets/b7e041b0-b634-4d67-b665-fd85d49100d8.png";
import IBMKeyboardImg from "../assets/50b6547d-ceb7-4d1e-8eff-191c2dd41bfd.png";
import PolaroidCameraImg from "../assets/10b36f41-5197-40d2-89ff-d4c41b46cc99.png";
import KodakBrownieImg from "../assets/7d039ac5-78b6-4488-b6fa-7d023ff35565.png";
import GrundigTubeRadioImg from "../assets/9c9a3c3b-4a77-40fc-bb7e-322daa40905a.png";
import BraunT3PocketCalculatorImg from "../assets/f5795f42-717f-4e3f-be3c-0d451a7cbfd3.png";
import SmithCoronaTypewriterImg from "../assets/e7a1b003-b11b-40dc-ac24-a4f120db41e1.png";
import LeicaM3Img from "../assets/210d3137-697e-442d-85e8-aa2c9779b3fd.png";
import PanasonicRX5600Img from "../assets/c87d93c9-85ab-436e-ae37-5b021e7365b2.png";
import ZenithRadioImg from "../assets/28764e24-8dfa-4e64-9334-b990e630dbed.png";
import FilmCineCamImg from "../assets/af58ab34-62ef-4677-8422-7e0e087f7a03.png";
import PolaroidLandCameraImg from "../assets/cf699d51-fee6-4ba7-9929-f10df12918ab.png";
import RevoxTapeRecorderImg from "../assets/61347e7b-20e9-4ee5-9c0e-1b84662256cb.png";
import Marantz2270Img from "../assets/4a2c82e6-1d1b-427c-8a3e-fa54f8a40af3.png";
import NESImg from "../assets/e17c21bd-98ac-4424-8249-483dae601bdc.png";
import Atari2600Img from "../assets/b78cd3fe-1051-4a3a-a68e-8772f6b4d613.png";
import VintageMacImg from "../assets/af31c4e5-5342-4c35-a0a1-cc4ae4475952.png";
import Comodore64Img from "../assets/9a8e0893-cac1-4db9-8ed4-ddd60a75e30e.png";
import Nokia3310MobileImg from "../assets/cf42d380-8fe2-4fba-9f1d-612ddd67cb32.png";
import TrinitronColorTVImg from "../assets/9a76ed10-83e1-46b5-ae7b-84c987cbfb8c.png";
import SchwinnBikeImg from "../assets/e9a0d1d1-8080-4cb6-befd-25b21a3b66dc.png";
import BOTurntableImg from "../assets/ffb366ff-6355-4a53-be33-ac4043de2b3a.png";
import NikonCameraF3Img from "../assets/c4211767-fa15-48cf-bd18-ebdbbd132a51.png";
import LesPaulGuitar from "../assets/0c4eccd5-3e20-4aba-b873-e193247a5bb4.png";
import GameBoy from "../assets/cd37a871-e3f1-4e23-b39b-930fd3d954a1.png";
import SeikoWatch from "../assets/5677da8f-abe5-4c7d-a471-4f966bc37635.png";
import SewingMachine from "../assets/b79320a1-2d17-4b64-90c7-d435d118c8ef.png";
import MilkshakeMixer from "../assets/bb78adce-f553-4d4b-9f96-d8525aff836a.png";
import ContaxG2 from "../assets/5e518672-8e49-47a0-81cd-841ff669002b.png";

const products = [
  {
    id: 1,
    text: "Vintage Sony Walkman",
    description: [
      "Classic portable cassette player",
      "Iconic design",
      "Revolutionized personal music listening",
      "Compact and lightweight",
      "Runs on AA batteries",
      "Includes original headphones",
    ],
    category: "Audio",
    price: 129.99,
    image: SonyWalkmanImg,
  },
  {
    id: 2,
    text: "Vintage Sennheiser HD414 Headphones",
    description: [
      "Legendary open-back headphones",
      "Rich sound quality",
      "First open-back headphone design",
      "Comfortable foam ear pads",
      "Lightweight and durable",
      "Iconic yellow ear pads",
    ],
    category: "Audio",
    price: 149.99,
    image: SennheiserHD414Img,
  },
  {
    id: 3,
    text: "Vintage IBM Model M Keyboard",
    description: [
      "Mechanical keyboard with buckling springs",
      "Tactile typing experience",
      "Highly durable build",
      "Known for its loud keystroke sound",
      "Detachable cable",
      "Iconic beige color",
    ],
    category: "Computer Accessories",
    price: 199.99,
    image: IBMKeyboardImg,
  },
  {
    id: 4,
    text: "Vintage Polaroid SX-70 Instant Camera",
    description: [
      "Iconic folding instant camera",
      "Produces classic instant photos",
      "First SLR instant camera",
      "Automatic exposure control",
      "Compact and portable",
      "Retro design appeal",
    ],
    category: "Cameras",
    price: 299.99,
    image: PolaroidCameraImg,
  },
  {
    id: 5,
    text: "Vintage Kodak Brownie Hawkeye Camera",
    description: [
      "Classic box camera design",
      "Uses 620 film format",
      "Easy to use",
      "Durable plastic body",
      "Fixed-focus lens",
      "Introduced in the 1950s",
    ],
    category: "Cameras",
    price: 79.99,
    image: KodakBrownieImg,
  },
  {
    id: 6,
    text: "Vintage Grundig Tube Radio",
    description: [
      "Beautiful wooden cabinet design",
      "Warm tube sound",
      "Classic mid-century design",
      "AM/FM tuning",
      "High-quality craftsmanship",
      "Perfect for vintage audio enthusiasts",
    ],
    category: "Audio",
    price: 299.99,
    image: GrundigTubeRadioImg,
  },
  {
    id: 7,
    text: "Vintage Braun T3 Pocket Calculator",
    description: [
      "Slim and stylish pocket calculator",
      "Classic design by Dieter Rams",
      "Simple and functional",
      "Easy-to-read display",
      "Battery-powered",
      "Timeless aesthetic",
    ],
    category: "Calculators",
    price: 59.99,
    image: BraunT3PocketCalculatorImg,
  },
  {
    id: 8,
    text: "Vintage Smith-Corona Typewriter",
    description: [
      "Classic manual typewriter",
      "Timeless typing experience",
      "Durable and reliable",
      "Portable design",
      "Ribbon-based typing",
      "Favored by writers and collectors",
    ],
    category: "Office Equipment",
    price: 199.99,
    image: SmithCoronaTypewriterImg,
  },
  {
    id: 9,
    text: "Vintage Leica M3 Camera",
    description: [
      "Legendary rangefinder camera",
      "Exceptional build quality",
      "Renowned for its optics",
      "Compact and durable",
      "Manual focus and exposure",
      "Highly sought after by photographers",
    ],
    category: "Cameras",
    price: 1999.99,
    image: LeicaM3Img,
  },
  {
    id: 10,
    text: "Vintage Panasonic RX-5600 Boombox",
    description: [
      "Powerful portable cassette player",
      "Retractable handle and detachable speakers",
      "AM/FM radio",
      "Dual cassette decks",
      "High-quality sound",
      "Iconic 1980s design",
    ],
    category: "Audio",
    price: 499.99,
    image: PanasonicRX5600Img,
  },
  {
    id: 11,
    text: "Vintage Zenith Trans-Oceanic Radio",
    description: [
      "Classic shortwave radio",
      "Built-in antenna and wood case",
      "Multiple band reception",
      "High-quality craftsmanship",
      "Portable with handle",
      "Perfect for radio enthusiasts",
    ],
    category: "Audio",
    price: 399.99,
    image: ZenithRadioImg,
  },
  {
    id: 12,
    text: "Vintage Bolex 581 Sound Macrozoom Camera",
    description: [
      "Italian-designed portable typewriter",
      "Distinctive red color and compact design",
      "Versatile zoom lens",
      "Sync sound recording capability",
      "Highly collectible",
      "Used for amateur filmmaking",
    ],
    category: "Cameras",
    price: 499.99,
    image: FilmCineCamImg,
  },
  {
    id: 13,
    text: "Vintage Polaroid Land Camera Model 100",
    description: [
      "Instant camera with folding bellows design",
      "Uses peel-apart instant film",
      "Manual focus and exposure",
      "Flash attachment included",
      "Retro appearance",
      "Popular in the 1960s",
    ],
    category: "Cameras",
    price: 249.99,
    image: PolaroidLandCameraImg,
  },
  {
    id: 14,
    text: "Vintage Revox A77 Reel-to-Reel Tape Recorder",
    description: [
      "High-end reel-to-reel tape recorder",
      "Studio-quality audio playback",
      "Durable build",
      "Two-track recording capability",
      "Smooth tape transport",
      "Popular in professional studios",
    ],
    category: "Audio",
    price: 999.99,
    image: RevoxTapeRecorderImg,
  },
  {
    id: 15,
    text: "Vintage Marantz 2270 Stereo Receiver",
    description: [
      "Classic silver-faced stereo receiver",
      "Warm and detailed sound reproduction",
      "High-quality build",
      "AM/FM radio tuner",
      "Dual speaker outputs",
      "Coveted by audiophiles",
    ],
    category: "Audio",
    price: 899.99,
    image: Marantz2270Img,
  },
  {
    id: 16,
    text: "Vintage Nintendo Entertainment System (NES)",
    description: [
      "Iconic 8-bit gaming console",
      "Includes two controllers and Zapper gun",
      "Original game library",
      "Classic grey design",
      "Revolutionized home gaming",
      "First released in the mid-1980s",
    ],
    category: "Gaming",
    price: 199.99,
    image: NESImg,
  },
  {
    id: 17,
    text: "Vintage Atari 2600 Console",
    description: [
      "Classic video game console",
      "Includes joystick and paddle controllers",
      "Simple yet addictive games",
      "Durable and reliable",
      "Introduced in the late 1970s",
      "Nostalgic value",
    ],
    category: "Gaming",
    price: 249.99,
    image: Atari2600Img,
  },
  {
    id: 18,
    text: "Vintage Apple Macintosh Plus Computer",
    description: [
      "Iconic all-in-one desktop computer",
      "Built-in 9-inch monochrome display",
      "Early graphical user interface",
      "Compact design",
      "1MB of RAM",
      "Introduced in 1986",
    ],
    category: "Computers",
    price: 1099.99,
    image: VintageMacImg,
  },
  {
    id: 19,
    text: "Vintage Commodore 64 Computer",
    description: [
      "Legendary home computer",
      "Popular for gaming and programming",
      "64KB of RAM",
      "8-bit microprocessor",
      "Wide software library",
      "First released in 1982",
    ],
    category: "Computers",
    price: 799.99,
    image: Comodore64Img,
  },
  {
    id: 20,
    text: "Vintage Nokia 3310 Cell Phone",
    description: [
      "Indestructible mobile phone",
      "Long-lasting battery life",
      "Simple and reliable",
      "Iconic design",
      "Pre-loaded with Snake game",
      "Popular in the early 2000s",
    ],
    category: "Phones",
    price: 79.99,
    image: Nokia3310MobileImg,
  },
  {
    id: 21,
    text: "Vintage Sony Trinitron Color TV",
    description: [
      "Iconic CRT television",
      "Superb color reproduction",
      "Durable and reliable",
      "Multiple input options",
      "Popular in the 1980s",
      "Renowned picture quality",
    ],
    category: "Electronics",
    price: 599.99,
    image: TrinitronColorTVImg,
  },
  {
    id: 22,
    text: "Vintage Bang & Olufsen Beogram Turntable",
    description: [
      "High-end belt-driven turntable",
      "Sleek aluminum design",
      "Precision sound quality",
      "Automatic tonearm",
      "Stylish and modern",
      "Coveted by audiophiles",
    ],
    category: "Audio",
    price: 899.99,
    image: BOTurntableImg,
  },
  {
    id: 23,
    text: "Vintage Schwinn Bicycle",
    description: [
      "Iconic American bicycle",
      "Durable and stylish",
      "Classic frame design",
      "Reliable performance",
      "Suitable for various terrains",
      "Popular throughout the 20th century",
    ],
    category: "Outdoor Recreation",
    price: 499.99,
    image: SchwinnBikeImg,
  },
  {
    id: 24,
    text: "Vintage Nikon F3",
    description: [
      "Classic rangefinder camera",
      "Timeless design and exceptional optics",
      "Durable and reliable",
      "Manual focus and exposure",
      "Popular with professional photographers",
      "Released in the early 1980s",
    ],
    category: "Cameras",
    price: 799.99,
    image: NikonCameraF3Img,
  },
  {
    id: 25,
    text: "Vintage Gibson Les Paul Guitar",
    description: [
      "Iconic electric guitar",
      "Rich tone and superb craftsmanship",
      "Solid mahogany body",
      "Popular with rock musicians",
      "Classic sunburst finish",
      "Highly collectible",
    ],
    category: "Musical Instruments",
    price: 3999.99,
    image: LesPaulGuitar,
  },
  {
    id: 26,
    text: "Vintage GameBoy Handheld Console",
    description: [
      "Classic handheld gaming console",
      "Monochrome display",
      "Long battery life",
      "Compact and portable",
      "Released in 1989",
      "Includes iconic games like Tetris",
    ],
    category: "Gaming",
    price: 199.99,
    image: GameBoy,
  },
  {
    id: 27,
    text: "Vintage Seiko Pogue Chronograph Watch",
    description: [
      "Legendary Seiko chronograph",
      "Distinctive yellow dial and 70s styling",
      "Automatic movement",
      "Durable stainless steel case",
      "First automatic chronograph in space",
      "Highly collectible",
    ],
    category: "Watches",
    price: 1499.99,
    image: SeikoWatch,
  },
  {
    id: 28,
    text: "Vintage Singer Featherweight Sewing Machine",
    description: [
      "Iconic portable sewing machine",
      "Reliable and precise stitching",
      "Lightweight and durable",
      "Easy to use",
      "Highly sought after by collectors",
      "Introduced in the 1930s",
    ],
    category: "Crafts",
    price: 299.99,
    image: SewingMachine,
  },
  {
    id: 29,
    text: "Vintage Hamilton Beach Milkshake Mixer",
    description: [
      "Iconic milkshake mixer",
      "Perfect for retro soda fountain vibes",
      "Durable stainless steel construction",
      "Powerful mixing motor",
      "Classic 1950s design",
      "Easy to clean",
      "Produces thick and creamy milkshakes",
    ],
    category: "Kitchen Appliances",
    price: 79.99,
    image: MilkshakeMixer,
  },
  {
    id: 30,
    text: "Vintage Contax G2 Camera",
    description: [
      "High-end 35mm film rangefinder camera",
      "Autofocus and manual focus options",
      "Durable titanium body",
      "Exceptional lens quality",
      "Compact and portable",
      "Popular among professional photographers",
    ],
    category: "Cameras",
    price: 1699.99,
    image: ContaxG2,
  },
];

export default products;
